# Generated by Django 5.0.7 on 2024-08-07 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniapp', '0007_cart_item_total'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('streetAddress', models.CharField(max_length=100)),
                ('optionalAddress', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phoneNo', models.IntegerField()),
                ('posta_Zip', models.CharField(max_length=50)),
                ('OrderNotes', models.CharField(max_length=500)),
                ('Cart_Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furniapp.cart_item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
