# Generated by Django 5.0.7 on 2024-08-12 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniapp', '0011_remove_cart_item_status_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Cart_Item',
        ),
    ]
