# Generated by Django 5.0.7 on 2024-08-16 12:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('price', models.IntegerField()),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team_Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('ExecutiveTestimonials', models.CharField(max_length=300, null=True)),
                ('img', models.ImageField(upload_to='team_members')),
            ],
        ),
        migrations.CreateModel(
            name='Cart_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('productName', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField()),
                ('offer', models.BooleanField(default=False)),
                ('img', models.ImageField(upload_to='orders')),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('total', models.FloatField(default=0.0)),
                ('customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='furniapp.furniture')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=36)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('streetAddress', models.CharField(max_length=100)),
                ('optionalAddress', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNo', models.IntegerField()),
                ('posta_Zip', models.CharField(max_length=50)),
                ('OrderNotes', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Placed', 'Placed'), ('Delivered', 'Delivered')], default='Pending', max_length=10)),
                ('ProductName', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('total', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
