# Generated by Django 5.0.7 on 2024-08-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phoneNo2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
