# Generated by Django 5.0.7 on 2024-08-18 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniapp', '0002_mode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mode',
        ),
    ]
