# Generated by Django 5.0.7 on 2024-08-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniapp', '0003_delete_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phoneNo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phoneNo2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subscriberOfNewsletter',
            field=models.BooleanField(null=True),
        ),
    ]
