# Generated by Django 5.0.7 on 2024-08-19 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniapp', '0004_alter_customuser_birth_date_alter_customuser_phoneno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_item',
            name='date',
        ),
    ]
