# Generated by Django 5.0.7 on 2024-07-29 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniapp', '0005_remove_cart_item_name_cart_item_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='productName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cart_item',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
