# Generated by Django 5.0.7 on 2024-08-19 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniapp', '0006_orders_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='date',
            new_name='dateOforders',
        ),
    ]
