# Generated by Django 5.0.7 on 2024-08-20 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniapp', '0007_rename_date_orders_dateoforders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='furniapp.furniture'),
        ),
    ]
