# Generated by Django 5.0.7 on 2024-08-20 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniapp', '0008_orders_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_item',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='quantity',
        ),
    ]
