# Generated by Django 5.0.7 on 2024-08-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniapp', '0008_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='totalAmount',
            field=models.FloatField(default=0.0),
        ),
    ]
