# Generated by Django 5.0.7 on 2024-08-07 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniapp', '0009_cart_item_totalamount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_item',
            name='totalAmount',
        ),
    ]
