# Generated by Django 5.0.7 on 2024-08-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniapp', '0009_remove_cart_item_price_remove_orders_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_item',
            name='productName',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='ProductName',
        ),
        migrations.AlterField(
            model_name='furniture',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
