# Generated by Django 5.0.7 on 2024-08-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniapp', '0010_remove_cart_item_totalamount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_item',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Placed', 'Placed'), ('Delivered', 'Delivered')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
